server:
  port: 9527

spring:
  application:
    name: config-server
  # spring cloud config
  cloud:
    config:
      server:
        # git 的 远程仓库地址
        git:
#          #使用https的链接
          uri: https://gitee.com/lichengen521/config.git
          #如果仓库是私有的 就要配置用户名和密码
          force-pull: true
          username: lichengen521
          password: qq960719

      label: master # 分支配置

  #配置rabbitmq的信息 因为bus集成rabbitmq 消息中间件来实现消息的发送 所以要配置对应的rabbitmq的信息、
  rabbitmq:
    host: 172.31.11.15
    port: 5672
    username: guest
    password: guest
    virtual-host: /

#暴露bus的刷新端点 curl -X POST http://localhost:9527/actuator/bus-refresh 然后跑一边config-server的命令即可实现全部刷新配置
management:
  endpoints:
    web:
      exposure:
        include: "bus-refresh"
#将自己注册到eureka中
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
